"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

import os
from setuptools import setup

VERSION = ""

filename = "version.py"
exec(open(filename).read())

print(VERSION)

currentDirectory = os.path.dirname(os.path.realpath(__file__))

APP = ['bin/encoder.py']
DATA_FILES = ['icon/icon.icns']
OPTIONS = {'argv_emulation': True,
 'iconfile': os.path.join(currentDirectory, '../icon/icon.icns'),
 'plist': {'CFBundleDevelopmentRegion': 'English',
           'CFBundleDisplayName': 'Sermons Encoder',
           'CFBundleDocumentTypes': [{'CFBundleTypeOSTypes': ['****',
                                                              'fold',
                                                              'disk'],
                                      'CFBundleTypeRole': 'Viewer'}],
           'CFBundleExecutable': 'encoder',
           'CFBundleIconFile': 'PythonApplet.icns',
           'CFBundleIdentifier': 'au.id.jamesmckay.encoder',
           'CFBundleInfoDictionaryVersion': '6.0',
           'CFBundleName': 'Sermons Encoder',
           'CFBundlePackageType': 'APPL',
           'CFBundleShortVersionString': VERSION,
           'CFBundleSignature': '????',
           'CFBundleVersion': VERSION,
           'LSHasLocalizedDisplayName': False,
           'NSAppleScriptEnabled': False,
           'NSHumanReadableCopyright': 'Copyright not specified',
           'NSMainNibFile': 'MainMenu',
           'NSPrincipalClass': 'NSApplication',
           'PyMainFileNames': ['__boot__'],
           'PyOptions': {'alias': True,
                         'argv_emulation': True,
                         'emulate_shell_environment': False,
                         'no_chdir': False,
                         'prefer_ppc': False,
                         'site_packages': False,
                         'use_faulthandler': False,
                         'use_pythonpath': False,
                         'verbose': False},
           'PyResourcePackages': [],
           'PyRuntimeLocations': ['@executable_path/../Frameworks/Python.framework/Versions/3.4/Python',
                                  '/Library/Frameworks/Python.framework/Versions/3.4/Python'],
           'PythonInfoDict': {'PythonExecutable': '/Library/Frameworks/Python.framework/Versions/3.4/bin/python3',
                              'PythonLongVersion': '3.4.1 '
                                                   '(v3.4.1:c0e311e010fc, '
                                                   'May 18 2014, '
                                                   '00:54:21) \n'
                                                   '[GCC 4.2.1 (Apple Inc. '
                                                   'build 5666) (dot 3)]',
                              'PythonShortVersion': '3.4',
                              'py2app': {'alias': True,
                                         'template': 'app',
                                         'version': '0.8.1'}}}}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
